sudo: false
dist: trusty
language: node_js
node_js: lts/*
install:
  - travis_retry gem install s3_website -v 3.4.0
  - travis_retry npm ci
script:
  - webpack
  - WEBPACK_TARGET=lib webpack
  - npm run lint
  - npm run test
#  Disable integration tests while portal-report is being refactored to support new data format and Firebase
#  - npm run start &
#  - wait-on http://localhost:8080
#  - $(npm bin)/cypress run --config video=false
after_success:
  - ./s3_deploy.sh
cache:
  bundler: true
  npm: true
  directories:
    - ~/.cache
