sudo: false
dist: trusty
language: node_js
node_js: lts/*
install:
  - travis_retry gem install s3_website -v 3.4.0
  - travis_retry npm ci
script:
  - webpack
  - WEBPACK_TARGET=lib webpack
  - npm run test
  - npm run start &
  - wait-on http://localhost:8080
  - $(npm bin)/cypress run --config video=false
  - ./s3_deploy.sh
cache:
  bundler: true
  npm: true
  directories:
    - ~/.cache
