sudo: false
language:
  - node_js
  - ruby
node_js:
  - node
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - travis_retry gem install s3_website -v 3.4.0
  - travis_retry npm install
before_script:
  - webpack
  - WEBPACK_TARGET=lib webpack
script:
  - npm run test
  - npm run server &
  - cypress install
  - wait-on http://localhost:8080
  - $(npm bin)/cypress run --config video=false
  - ./s3_deploy.sh
cache:
  bundler: true
  directories:
    - node_modules
